import { STYLES } from './styles.js';
import { escapeHtml } from '../utils/escape-html.js';
import type { DashboardMeta } from '../types/render-context.js';

export function assembleHtmlDoc(meta: DashboardMeta, sections: string[]): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>IvyFlow Dashboard — ${escapeHtml(meta.repository)}</title>
  <style>${STYLES}</style>
</head>
<body>
${sections.join('\n')}
<footer>
  Generated by IvyFlow | Model: ${escapeHtml(meta.model)} | ${new Date().toISOString()}
</footer>
</body>
</html>`;
}
