/**
 * Format Converter — converts IvyFlow rules to platform-specific formats.
 *
 * v0.33: Enables `ivy sync` to distribute .ai-rules/ content to
 * Claude Code, Cursor, CodeBuddy, and other platform formats.
 */

import type { Platform } from './platforms.js';

export interface PlatformFormatConverter {
  /** Human-readable name for this converter */
  name: string;
  /** Target platform ID (matches PLATFORMS[].id) */
  platformId: string;
  /** Convert a set of rule files to the platform's format */
  convert(rules: Array<{ path: string; content: string }>): string;
  /** Where to write the converted output, relative to project root */
  targetPath(platform: Platform): string;
}

/** Convert rules to Claude Code CLAUDE.md format */
export const claudeCodeConverter: PlatformFormatConverter = {
  name: 'Claude Code',
  platformId: 'claude',
  convert(rules) {
    const lines: string[] = [];
    lines.push('# IvyFlow Rules (auto-generated by ivy sync)');
    lines.push('');
    for (const rule of rules) {
      lines.push(`## ${rule.path}`);
      lines.push('');
      lines.push(rule.content);
      lines.push('');
    }
    return lines.join('\n');
  },
  targetPath() {
    return 'CLAUDE.md';
  },
};

/** Convert rules to Cursor .cursor/rules/ format */
export const cursorConverter: PlatformFormatConverter = {
  name: 'Cursor',
  platformId: 'cursor',
  convert(rules) {
    const lines: string[] = [];
    for (const rule of rules) {
      lines.push(`# ${rule.path.replace('.md', '').replace(/-/g, ' ')}`);
      lines.push('');
      lines.push(rule.content);
      lines.push('');
    }
    return lines.join('\n');
  },
  targetPath() {
    return '.cursor/rules/ivy-rules.md';
  },
};

/** Convert rules to CodeBuddy .codebuddy/ format */
export const codebuddyConverter: PlatformFormatConverter = {
  name: 'CodeBuddy',
  platformId: 'codebuddy',
  convert(rules) {
    const lines: string[] = [];
    lines.push('---');
    lines.push('description: IvyFlow Rules (auto-generated)');
    lines.push('globs: **/*');
    lines.push('---');
    lines.push('');
    for (const rule of rules) {
      lines.push(rule.content);
      lines.push('');
    }
    return lines.join('\n');
  },
  targetPath() {
    return '.codebuddy/rules/ivy-rules.md';
  },
};

export const ALL_CONVERTERS: PlatformFormatConverter[] = [
  claudeCodeConverter,
  cursorConverter,
  codebuddyConverter,
];

export function getConvertersForPlatforms(platformIds: string[]): PlatformFormatConverter[] {
  if (platformIds.length === 0) return ALL_CONVERTERS;
  return ALL_CONVERTERS.filter((c) => platformIds.includes(c.platformId));
}
