import { execSync } from 'child_process';
import { logger } from '../utils/logger.js';

export interface OpenSpecBridgeOptions {
  changeName: string;
  cwd: string;
}

export type OpenSpecEvent = 'proposed' | 'applied' | 'archived';

export interface PhaseRecommendation {
  target: string;
  message: string;
  command: string;
}

interface OpenSpecArtifact {
  id: string;
  status: string;
  deps: string[];
}

interface OpenSpecStatus {
  schemaName: string;
  applyRequires: string[];
  artifacts: OpenSpecArtifact[];
}

export class OpenSpecBridge {
  private opts: OpenSpecBridgeOptions;

  constructor(opts: OpenSpecBridgeOptions) {
    this.opts = opts;
  }

  async translateEvent(event: OpenSpecEvent, changeName: string): Promise<PhaseRecommendation> {
    switch (event) {
      case 'proposed':
        return {
          target: 'design',
          message: `Proposal "${changeName}" created. Recommended phase: DESIGN`,
          command: 'ivy state set design',
        };
      case 'applied':
        return {
          target: 'verify',
          message: `Implementation "${changeName}" complete. Recommended phase: VERIFY`,
          command: 'ivy state set verify',
        };
      case 'archived': {
        const hasWorktree = this.checkWorktree(changeName);
        if (hasWorktree) {
          return {
            target: 'archive',
            message: `Change "${changeName}" archived. Worktree found. Run: ivy worktree cleanup ${changeName}`,
            command: `ivy worktree cleanup ${changeName}`,
          };
        }
        return {
          target: 'archive',
          message: `Change "${changeName}" archived.`,
          command: '',
        };
      }
    }
  }

  async recommendPhase(recommendation: PhaseRecommendation): Promise<void> {
    logger.header('Phase Recommendation');
    logger.divider();
    logger.info(`  ${recommendation.message}`);
    if (recommendation.command) {
      logger.info('');
      logger.info(`  Run: \`${recommendation.command}\``);
      logger.info('  (Phase will NOT be auto-promoted — user confirmation required)');
    }
    logger.divider();
  }

  /**
   * Get artifact dependency graph from OpenSpec status.
   * Returns the parsed status and a list of artifact dependency levels for parallel generation.
   */
  private getArtifactStatus(): OpenSpecStatus | null {
    try {
      const output = execSync(`openspec status --change "${this.opts.changeName}" --json`, {
        cwd: this.opts.cwd,
        encoding: 'utf-8',
      });
      return JSON.parse(output) as OpenSpecStatus;
    } catch {
      return null;
    }
  }

  /**
   * Generate artifacts in parallel respecting dependency DAG.
   * Returns the number of artifacts successfully generated.
   */
  async generateArtifactsParallel(changeName: string): Promise<number> {
    const status = this.getArtifactStatus();
    if (!status) {
      logger.warn('Could not read OpenSpec status — falling back to sequential generation.');
      return 0;
    }

    const artifacts = status.artifacts;
    const completed = new Set<string>();
    const MAX_PARALLEL = 3;
    let totalGenerated = 0;

    while (completed.size < artifacts.length) {
      // Find artifacts whose dependencies are satisfied and not yet completed
      const ready = artifacts.filter(
        (a) =>
          a.status !== 'done' &&
          !completed.has(a.id) &&
          (a.deps ?? []).every((d) => completed.has(d) || artifacts.find((ad) => ad.id === d)?.status === 'done'),
      );

      if (ready.length === 0) break;

      // Generate ready artifacts in parallel (up to MAX_PARALLEL)
      const batch = ready.slice(0, MAX_PARALLEL);
      const results = await Promise.allSettled(
        batch.map((a) => this.generateSingleArtifact(a.id)),
      );

      for (let i = 0; i < batch.length; i++) {
        if (results[i].status === 'fulfilled') {
          completed.add(batch[i].id);
          totalGenerated++;
          logger.success(`  Generated artifact: ${batch[i].id}`);
        } else {
          logger.warn(`  Failed to generate artifact ${batch[i].id}: ${(results[i] as PromiseRejectedResult).reason}`);
        }
      }
    }

    return totalGenerated;
  }

  /**
   * Generate a single artifact using openspec instructions.
   */
  private async generateSingleArtifact(artifactId: string): Promise<void> {
    // Get instructions from OpenSpec
    const instructionsOutput = execSync(
      `openspec instructions "${artifactId}" --change "${this.opts.changeName}" --json`,
      { cwd: this.opts.cwd, encoding: 'utf-8' },
    );
    const instructions = JSON.parse(instructionsOutput);

    // The artifact is generated by following the template and instruction
    // For parallel mode, we delegate to openspec generate
    execSync(
      `openspec generate "${artifactId}" --change "${this.opts.changeName}"`,
      { cwd: this.opts.cwd, stdio: 'pipe' },
    );
  }

  private checkWorktree(changeName: string): boolean {
    try {
      const output = execSync('git worktree list', {
        cwd: this.opts.cwd,
        encoding: 'utf-8',
      });
      return output.split('\n').some((line) => line.includes(changeName));
    } catch {
      return false;
    }
  }
}
